spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/predicktions_test}
    username: ${DB_USERNAME:predicktions}
    password: ${DB_PASSWORD:predicktions}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true

jwt:
  secret: "test-secret-key-that-is-at-least-32-bytes-long-123456"
  expiration: 3600000

server:
  port: 0

logging:
  level:
    com.ven.predicktions: INFO