spring:
  application:
    name: predicktions

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  config:
    import: optional:file:.env[.properties]

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}

sports:
  football-data:
    api-token: ${FOOTBALL_DATA_API_TOKEN}

  sync:
    competition-code: CL
    fixtures-cron: "0 0 1 1 * *"
    results-cron: "0 30 22 * * *"

    fixture-schedules:
      - phase: LEAGUE
        date: 2026-09-01

      - phase: KNOCKOUT_PLAYOFF
        date: 2027-01-30

      - phase: ROUND_OF_16
        date: 2027-02-27

      - phase: QUARTER_FINAL
        date: 2027-03-18

      - phase: SEMI_FINAL
        date: 2027-04-15

      - phase: FINAL
        date: 2027-05-06

    result-schedules:
      # League phase
      - matchday: 1
        date: 2026-09-08

      - matchday: 1
        date: 2026-09-09

      - matchday: 1
        date: 2026-09-10

      - matchday: 2
        date: 2026-10-13

      - matchday: 2
        date: 2026-10-14

      - matchday: 3
        date: 2026-10-20

      - matchday: 3
        date: 2026-10-21

      - matchday: 4
        date: 2026-11-03

      - matchday: 4
        date: 2026-11-04

      - matchday: 5
        date: 2026-11-24

      - matchday: 5
        date: 2026-11-25

      - matchday: 6
        date: 2026-12-08

      - matchday: 6
        date: 2026-12-09

      - matchday: 7
        date: 2027-01-19

      - matchday: 7
        date: 2027-01-20

      - matchday: 8
        date: 2027-01-27

      # Knockout phase play-offs
      - matchday: 9
        date: 2027-02-16
      - matchday: 9
        date: 2027-02-17
      - matchday: 9
        date: 2027-02-23
      - matchday: 9
        date: 2027-02-24

      # Round of 16
      - matchday: 10
        date: 2027-03-09
      - matchday: 10
        date: 2027-03-10
      - matchday: 10
        date: 2027-03-16
      - matchday: 10
        date: 2027-03-17

      # Quarter-finals
      - matchday: 11
        date: 2027-04-06
      - matchday: 11
        date: 2027-04-07
      - matchday: 11
        date: 2027-04-13
      - matchday: 11
        date: 2027-04-14

      # Semi-finals
      - matchday: 12
        date: 2027-04-27
      - matchday: 12
        date: 2027-04-28
      - matchday: 12
        date: 2027-05-04
      - matchday: 12
        date: 2027-05-05

      # Final
      - matchday: 13
        date: 2027-06-05