package com.ven.predicktions.model;

public enum AdminAuditAction {
    ROLE_CHANGED,
    USER_ENABLED,
    USER_DISABLED,
    POINTS_ADJUSTED,
    MATCH_RESULT_CHANGED,
    PREDICTION_MODIFIED,
    PREDICTIONS_RECALCULATED,
    LEAGUE_DELETED,
    LEAGUE_MEMBER_REMOVED,
    LEADERBOARD_RECALCULATED
}
